# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 565)
        font = QtGui.QFont()
        font.setPointSize(6)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #1f70d3")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 821, 191))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: #ffff40")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, -150, 331, 461))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgonline-com-ua-Resize-TlAVzACsXR.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 591, 151))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #1E90FF")
        self.label_2.setObjectName("label_2")
        self.input_pib = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pib.setGeometry(QtCore.QRect(20, 200, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.input_pib.setFont(font)
        self.input_pib.setStyleSheet("bachground-color: #1f70d3;\n"
"border: 2px solid #ffff40;\n"
"border-radius: 15;\n"
"color: white")
        self.input_pib.setText("")
        self.input_pib.setAlignment(QtCore.Qt.AlignCenter)
        self.input_pib.setObjectName("input_pib")
        self.input_product = QtWidgets.QLineEdit(self.centralwidget)
        self.input_product.setGeometry(QtCore.QRect(20, 260, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.input_product.setFont(font)
        self.input_product.setStyleSheet("bachground-color: #1f70d3;\n"
"border: 2px solid #ffff40;\n"
"border-radius: 15;\n"
"color: white")
        self.input_product.setText("")
        self.input_product.setAlignment(QtCore.Qt.AlignCenter)
        self.input_product.setObjectName("input_product")
        self.input_servise = QtWidgets.QLineEdit(self.centralwidget)
        self.input_servise.setGeometry(QtCore.QRect(20, 320, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.input_servise.setFont(font)
        self.input_servise.setStyleSheet("bachground-color: #1f70d3;\n"
"border: 2px solid #ffff40;\n"
"border-radius: 15;\n"
"color: white")
        self.input_servise.setText("")
        self.input_servise.setAlignment(QtCore.Qt.AlignCenter)
        self.input_servise.setObjectName("input_servise")
        self.input_time = QtWidgets.QLineEdit(self.centralwidget)
        self.input_time.setGeometry(QtCore.QRect(20, 380, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.input_time.setFont(font)
        self.input_time.setStyleSheet("bachground-color: #1f70d3;\n"
"border: 2px solid #ffff40;\n"
"border-radius: 15;\n"
"color: white")
        self.input_time.setText("")
        self.input_time.setAlignment(QtCore.Qt.AlignCenter)
        self.input_time.setObjectName("input_time")
        self.input_cost = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cost.setGeometry(QtCore.QRect(20, 440, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.input_cost.setFont(font)
        self.input_cost.setStyleSheet("bachground-color: #1f70d3;\n"
"border: 2px solid #ffff40;\n"
"border-radius: 15;\n"
"color: white")
        self.input_cost.setText("")
        self.input_cost.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cost.setObjectName("input_cost")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 500, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #1f70d3;\n"
"border: 2px solid #ffff40;\n"
"border-radius: 15;\n"
"color: white\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #0f488c;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 200, 431, 271))
        font = QtGui.QFont()
        font.setFamily("Aqum")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("bachground-color: #1f70d3;\n"
"border: 2px solid #ffff40;\n"
"border-radius: 15;\n"
"color: white")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Генератор чека"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерувати чек"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
